# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=25)),
                ('pDesc', models.CharField(max_length=100)),
                ('pRating', models.IntegerField(max_length=5)),
                ('pQty', models.IntegerField(max_length=100)),
            ],
        ),
    ]
