# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pQty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pRating',
        ),
    ]
