# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180103_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wlUserName', models.CharField(max_length=25)),
                ('wlName', models.CharField(max_length=25)),
            ],
        ),
    ]
