# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180103_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pPrice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='pQty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='pRating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wlQty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
