# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180103_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pImage',
            field=models.ImageField(default='/media', upload_to='api/static/images/'),
        ),
    ]
