# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_wishlist_pimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='pImage',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wlName',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wlQty',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wlUserName',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='pImage',
            field=models.ImageField(default='/media', upload_to='static/images/'),
        ),
    ]
