# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180117_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.CharField(max_length=128),
        ),
    ]
